api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
providers:
  docker:
    exposedByDefault: false
    network: test
tls:
  options:
    foo:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384